name: Build Dioxus CLI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'DioxusLabs/Dioxus'
        ref: 'v0.5.6'

    - name: Build
      run: cargo build --package dioxus-cli --release

    - uses: actions/upload-artifact@v4
      with:
        name: dx-${{ matrix.os }}
        path: './target/release/dx*'
        if-no-files-found: 'error'
